name: conduit_orm
version: 0.0.1
description: api and cli tooling for the conduit-orm 
repository: https://github.com/bsutton/conduit-orm
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.0.0
  dcli: ^0.51.0
  path: ^1.0.0

dev_dependencies: 
  pedantic: ^1.0.0

